### PR TITLE
updated ui

### PR DESCRIPTION
**Pull request by Shubham185y**
Screenshot (76)
Screenshot (77)
Screenshot (78)

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
@Shubham185y this branch has conflict resolve it first

**Comment by Shubham185y** [comment]
How to resolve it? Can you help

**Comment by Riya14-dangra** [comment]
> How to resolve it? Can you help

Click on 'resolve conflicts ' try to solve the error in the code

**Comment by Shubham185y** [comment]
I have resolved the conflicts you can review it and merge it .

**Pull request merged**
