### PR TITLE
Updated Navbar

### PR DESCRIPTION
**Pull request by Atharvk7**
Changed the navbar and modified the dark and light modes of the website.

### CODE REVIEW

**Comment by Riya14-dangra** [comment]
> Changed the navbar and modified the dark and light modes of the website.

share the shapshot of your work

**Comment by Atharvk7** [comment]
Sure Riya

**Comment by Atharvk7** [comment]
You can see the snapshots here: 
Dark Mode : https://drive.google.com/file/d/1A1CMw7LP_jUEiq-B1XIgWZqX1PigIcRx/view?usp=share_link
Light Mode: https://drive.google.com/file/d/1EZR-gLpsvHGIP2_CnK1Wdfnc7HeX8phl/view?usp=share_link

Thank you

**Comment by Atharvk7** [comment]
Hello Riya
Please merge this PR as the merge conflict is trivial I checked it.

**Pull request closed without merging**
